name: Publish to npm

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    environment:
      name: 'npm-packages'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Lint node package
        run: npm run lint

      - name: Build node package
        run: npm run build

      - name: Publish to npm with provenance
        run: npm publish --access public --provenance --ignore-scripts